[package]
org = "gateway"
name = "api_gateway"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.9.0"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.9.0"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.4.0"

[[dependency]]
org = "ballerina"
name = "sql"
version = "1.9.0"

[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.9.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.6.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.3.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.8.0"

[[dependency]]
org = "ballerina"
name = "regex"
version = "1.4.0"